dbt_test:
  target: dev
  outputs:
    dev:
      type: databricks
      host:dbc-6e076fbc-a34a.cloud.databricks.com
      http_path: /sql/1.0/warehouses/bf591fbe703288b3
      catalog: chatbot_poc
      schema: chatbot_data
      token: dapi569fa423c516af9adb51636dd34f2e2f